### ISSUE TITLE
issue with wlan and ultra96v2

### ISSUE THREAD

**Issue by SarahWicker** [ikwzm/ZynqMP-FPGA-Linux#4]
Hi :)
i used your files and indication to build new boot files for my ultra96v2 board but i have a problem concerning the WiFi.
The driver is well initialised but it seems that the p2p0 doesn't manage to get linked:

```
[   84.404171] WILC POWER UP
[   84.406841] wilc_sdio mmc1:0001:1: SDIO speed: 50000000
[   84.412449] wilc_sdio mmc1:0001:1: chipid 003000d0
[   92.909087] NOHZ: local_softirq_pending 08
[   94.647865] NOHZ: local_softirq_pending 08
[   96.388454] NOHZ: local_softirq_pending 08
[   98.129739] NOHZ: local_softirq_pending 08
[  111.033941] NOHZ: local_softirq_pending 08
[  111.982961] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
[  112.874685] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
[  113.085536] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
[  113.382381] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
[  113.680385] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
[  113.984808] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
```
and it goes on like this for a bit, at one point it stops and i tried to do a ifconfig but it stayed stock.
I am trying to connect to the WiFi generated by a raspberry pi… 
i wonder if the problem doesn't come from the fact that i can't generate an IP (tried to connect a pc to the WiFi as well and there figured taht no ip was generated)… and each time i tried the command sudo dhclient wlan0, Linux was freezing
As anyone encounter a similar issue?
BR
Sarah

**Comment by ikwzm** [comment]
Thank you for the issue.

However, I don't know much about p2p. I'm sorry I couldn't be of any use to you.

Are you trying to connect to RasberryPi in P2P mode?

Here is an example of P2P Mode settings on the Ultra96V2 WiFi chip (WILC3000).

 * https://github.com/atwilc3000/driver/wiki/WiFi#p2p-mode

How did you set it up?

Let me know if you know anything about this issue.

**Comment by SarahWicker** [comment]
Hi thank you a lot for your answer,
actually i am trying to connect via Wlan to the raspberry but as soon as my module (wilc_sdio) is loaded. It tries to link also the p2p0 module… which btw i don't remenber compiling.
the only way to stop it, is to put down both wlan0 and p2p0 interface.
I am currently looking thought the kernel configuration, when you configured your kernel image you didn't had this module compiled right?

i created the p2p_supplicant.conf file but when i execute the wpa_supplicant command it prints:

```
Successfully initialized wpa_supplicant
[  831.816356] IPv6: ADDRCONF(NETDEV_UP): p2p0: link is not ready
ctrl_iface exists and seems to be in use - cannot override it
Delete '/var/run/wpa_supplicant/p2p0' manually if it is not used anymore
Failed to initialize control interface '/var/run/wpa_supplicant'.
You may have another wpa_supplicant process already running or the file was
left by an unclean termination of wpa_supplicant in which case you will need
to manually remove this file before starting wpa_supplicant again.
```
And am not using ctrl_iface… 
after i get the same error message with link of p2p0 not been ready.

**Comment by SarahWicker** [comment]
Hello,
I managed to go a bit further using your base files. I can finally connect to wlan but this one doesn't hold. After 2-3min the connection get lost. iwconfig send me back that i am connect to my hotspot but when i try to ping it says that the network is unreachable… Did you already got this issue in the past?
Thank you a lot lot for your help
best regards
Sarah

**Comment by SarahWicker** [comment]
small update an to close this issue.
I manage to resolve my problem by  adding a gateway (apparently when i linked to my network, it wasn't created and after 2 min my connection was lost and couldn't be retrieved)
it is working great now, thank you a lot
best regards
