### ISSUE TITLE
qemu: Unsupported syscall: 276

### ISSUE THREAD

**Issue by coolicelee** [ikwzm/ZynqMP-FPGA-Linux#6]
I'm using your script to build rootfs, but I got the error :

> "qemu: Unsupported syscall: 276"

, when I run

> `dpkg -i linux-image-4.19.0-xlnx-v2019.2-zynqmp-fpga_4.19.0-xlnx-v2019.2-zynqmp-fpga-2_arm64.deb`

below is the full log:

> _dpkg -i linux-image-4.19.0-xlnx-v2019.2-zynqmp-fpga_4.19.0-xlnx-v2019.2-zynqmp-fpga-2_arm64.deb
> Selecting previously unselected package linux-image-4.19.0-xlnx-v2019.2-zynqmp-fpga.
> (Reading database ... 26393 files and directories currently installed.)
> Preparing to unpack linux-image-4.19.0-xlnx-v2019.2-zynqmp-fpga_4.19.0-xlnx-v2019.2-zynqmp-fpga-2_arm64.deb ...
> Unpacking linux-image-4.19.0-xlnx-v2019.2-zynqmp-fpga (4.19.0-xlnx-v2019.2-zynqmp-fpga-2) ...
> Setting up linux-image-4.19.0-xlnx-v2019.2-zynqmp-fpga (4.19.0-xlnx-v2019.2-zynqmp-fpga-2) ...
> qemu: Unsupported syscall: 276_

I get error not only for my own file, but also for file that I get from your repository with git lfs.
my host environment is Ubuntu 18.04 LTS 64 bits.
Could you please give me any advice, thanks a lot.

**Comment by ikwzm** [comment]
Thank you for the issue.

In the case of qumu, an error occurred, but there was no problem.
There is no problem if the debian package is installed correctly.

**Comment by coolicelee** [comment]
Thanks a lot for your answer.
